### PR TITLE
Styled tables in CSS

### PR DESCRIPTION
**Pull request by 96RadhikaJadhav**
This PR will resolve issue #5 .

### CODE REVIEW

**Comment by 96RadhikaJadhav** [comment]
@vasu-gondaliya I have styled both tables on the page, so it will look the same. Could you please review it?

**Comment by vasu-gondaliya** [comment]
@96RadhikaJadhav the tables look good. But I think it will look better if the colour scheme is dark based as the background is of that type too. What do you think?

**Comment by 96RadhikaJadhav** [comment]
> @96RadhikaJadhav the tables look good. But I think it will look better if the colour scheme is dark based as the background is of that type too. What do you think?

@vasu-gondaliya  If we make it dark it will look like no changes have been done. But if you feel it will look good in dark then I can make the changes.

**Comment by vasu-gondaliya** [comment]
@96RadhikaJadhav Something like this would look good. Or else you suggest some other style.

**Comment by 96RadhikaJadhav** [comment]
@vasu-gondaliya Colored one is looking good. I will try that.

**Comment by 96RadhikaJadhav** [comment]
image

See if this is looking good to you. Please let me know if you want it to change.

**Comment by vasu-gondaliya** [comment]
@96RadhikaJadhav Try the coloured one, I think it would look good. And first update the fork as many changes have been made.

**Comment by 96RadhikaJadhav** [comment]
@vasu-gondaliya  I made the changes. Can you please check  now?

**Comment by vasu-gondaliya** [comment]
I saw the added css but I am not able to see the coloured rows. I think you need to remove the background color properties of "td" elements. And can you use more vibrant colours? Check it out here https://www.schemecolor.com/tag/rainbow?trend . And remove the thick border.

**Comment by vasu-gondaliya** [comment]
Thank you everyone for the contributions!

**Pull request closed without merging**
