### PR TITLE
Styled the buttons in mobile view

### PR DESCRIPTION
**Pull request by ptechofficial**
3 files were updated, some divs and classes have also been added for styling purpose.

### CODE REVIEW

**Comment by ptechofficial** [comment]
@vasu-gondaliya Hey, is there a problem with this PR?

**Comment by vasu-gondaliya** [comment]
Yes, in the desktop view, the scramble string is overlapping with the cube. And the screen height is covering whole screen.
Screenshot from 2021-03-25 14-21-49

**Comment by vasu-gondaliya** [comment]
Don't make pull request of this many changes. Make smaller changes and push it.

**Comment by ptechofficial** [comment]
I am facing problems with the code being formatted in vs code. I have the whole code, but as soon as i commit, it shows an update in all the lines. @vasu-gondaliya

**Comment by ptechofficial** [comment]
And even if i turn it off, i don't think it will make any difference because the code which was formatted by vs code has been saved in my pc.

**Pull request closed without merging**
